services:
  - type: web
    name: agentic-workflow
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_SESSION_TOKEN
        sync: false
      - key: AWS_REGION
        value: ap-south-1
      - key: S3_BUCKET_NAME
        value: agentic-workflow-experiment
      - key: GOOGLE_API_KEY
        sync: false
